# Site settings
title: Análise de Dados 1
email: martha.menezes@ccc.ufcg.edu.br
description: > # this means to ignore newlines until "baseurl:"
  Resultados dos laboratórios da disciplina.
baseurl: "/AD1" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  michellymenezes
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
