---
title: "Problema 2 - Checkpoint 2"
output: 
  html_document:
    fig_width: 10
    fig_height: 8
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
require(ggplot2)

gastos <- read.table("ano-atual.csv", sep = ",", header = T, stringsAsFactors=FALSE)
despesaAerea <- subset(gastos, txtDescricao == "Emissão Bilhete Aéreo")
despesaTerceiros <- subset(despesaAerea, txtPassageiro != txNomeParlamentar)

despesaNoBSB <- subset(despesaAerea, !grepl("BSB", txtTrecho))
despesaNoBSB <- subset(despesaNoBSB, vlrDocumento > 0)

despesaNoBSB$txtPassageiro[despesaNoBSB$txtPassageiro != despesaNoBSB$txNomeParlamentar] <- "Terceiro"
despesaNoBSB$txtPassageiro[despesaNoBSB$txtPassageiro == despesaNoBSB$txNomeParlamentar] <- "Parlamentar"

despesaNoBSB$numMes[despesaNoBSB$numMes==1] <- "01 - Janeiro"
despesaNoBSB$numMes[despesaNoBSB$numMes==2] <- "02 - Fevereiro"
despesaNoBSB$numMes[despesaNoBSB$numMes==3] <- "03 - Março"
despesaNoBSB$numMes[despesaNoBSB$numMes==4] <- "04 - Abril"
despesaNoBSB$numMes[despesaNoBSB$numMes==5] <- "05 - Maio"

ggplot(despesaNoBSB, aes(txtPassageiro, vlrLiquido, color=txtPassageiro)) +  geom_point(position = position_jitter(width = .8), alpha = .3) + scale_color_manual(values = c("Parlamentar" = 'mediumorchid4','Terceiro' = 'orange')) + labs(title="Bilhetes aéreos de trechos além de BSB", x= "Mês", y="Valor do bilhete em R$", colour="Tipo de passageiro") + facet_grid(. ~
    numMes, scales = "free", space = "free")
```